esphome:
  name: ceas
  platformio_options:
    upload_speed: 921600
    board_build.flash_mode: dio
    board_build.f_flash: 80000000L
    board_build.f_cpu: 240000000L

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 16MB
  framework:
    type: esp-idf
    sdkconfig_options:
      COMPILER_OPTIMIZATION_SIZE: y
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: y
      CONFIG_ESP32S3_DATA_CACHE_64KB: y
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: y
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y

psram:
  mode: octal
  speed: 80MHz

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none

logger:

api:

ota:
  platform: esphome

spi:
  - type: quad
    clk_pin: 47
    data_pins: [21, 48, 40, 39]

i2c:
  - sda: 4
    scl: 8

output:
  - id: gpio_backlight_pwm
    platform: ledc
    pin: 1

light:
  - id: backlight
    name: Backlight
    platform: monochromatic
    output: gpio_backlight_pwm
    restore_mode: ALWAYS_ON

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Bucharest

# === INDEX CULOARE FUNDAL (NE-PERSISTENT) ===
globals:
  - id: bg_color_index
    type: int
    restore_value: no
    initial_value: '0'

font:
  - file: "fonts/digital-7.ttf"
    id: font_big
    size: 160

  - file: "fonts/digital-7.ttf"
    id: font_small
    size: 100

  - file: "fonts/DancingScript-VariableFont_wght.ttf"
    id: font_day
    size: 50

display:
  - id: main_display
    platform: mipi_spi
    model: JC3248W535
    data_rate: 40MHz
    rotation: 90
    update_interval: 1s
    auto_clear_enabled: true

    lambda: |-
      auto t = id(sntp_time).now();
      if (!t.is_valid()) return;

      // ==== CULORI POSIBILE ====
      Color colors[8] = {
        Color::BLACK,
        Color(255, 0, 0),
        Color(0, 255, 0),
        Color(0, 0, 255),
        Color(255, 255, 0),
        Color(0, 255, 255),
        Color(255, 0, 255),
        Color::WHITE
      };

      // ==== FUNDAL ====
      int idx = id(bg_color_index);
      if (idx < 0 || idx > 7) idx = 0;
      it.fill(colors[idx]);

      // ==== ORA & MINUTE ====
      char hm[16];
      t.strftime(hm, sizeof(hm), "%H:%M");

      // ==== SECUNDE ====
      char ss[8];
      t.strftime(ss, sizeof(ss), "%S");

      // ==== CALCUL LATIME HH:MM ====
      int x1, y1, w_hm, h1;
      it.get_text_bounds(0, 0, hm, id(font_big), TextAlign::TOP_LEFT, &x1, &y1, &w_hm, &h1);

      int spacing = 10;

      // ==== POZITII ====
      int x_hm = 20;
      int y_hm = 3;

      int x_ss = x_hm + w_hm + spacing;
      int y_ss = y_hm + 50;

      // ==== ORA & MINUTE CU UMBRA ====
      it.printf(x_hm + 3, y_hm + 3, id(font_big), Color::BLACK, TextAlign::LEFT, "%s", hm);
      it.printf(x_hm,     y_hm,     id(font_big), Color(255, 150, 200), TextAlign::LEFT, "%s", hm);

      // ==== SECUNDE CU UMBRA ====
      it.printf(x_ss + 3, y_ss + 3, id(font_small), Color::BLACK, TextAlign::LEFT, "%s", ss);
      it.printf(x_ss,     y_ss,     id(font_small), Color(255, 3, 123), TextAlign::LEFT, "%s", ss);

      // ==== ZIUA SĂPTĂMÂNII ====
      const char* zile[] = {
        "Duminica", "Luni", "Marti", "Miercuri",
        "Joi", "Vineri", "Sambata"
      };

      int zi_index = (t.day_of_week + 6) % 7;
      const char* ziua = zile[zi_index];

      // ==== ZI CU UMBRA ====
      it.printf(240 + 3, 180 + 3, id(font_day), Color::BLACK, TextAlign::CENTER, "%s", ziua);
      it.printf(240,     180,     id(font_day), Color(0, 200, 180), TextAlign::CENTER, "%s", ziua);

      // ==== DATA ====
      char datebuf[32];
      t.strftime(datebuf, sizeof(datebuf), "%d.%m.%Y");

      // ==== DATA CU UMBRA ====
      it.printf(240 + 3, 250 + 3, id(font_small), Color::BLACK, TextAlign::CENTER, "%s", datebuf);
      it.printf(240,     250,     id(font_small), Color(120, 255, 200), TextAlign::CENTER, "%s", datebuf);

touchscreen:
  - id: main_touchscreen
    platform: axs15231
    on_release:
      then:
        - lambda: |-
            id(bg_color_index)++;
            if (id(bg_color_index) > 7) id(bg_color_index) = 0;
